#! /usr/bin/env python
"""Shared configuration constants"""

version = ""
cdDriveLetter = ""
cdDeviceName = ""
reportFormatString = ""
isoBusterExe = ""
tempDir = ""
rootDir = ""
batchFolder = ""
batchManifest = ""
jobsFolder = ""
secondsToTimeout = ""
prefixBatch = ""
socketHost = "127.0.0.1"
socketPort = "65432"
enablePPNLookup = True
enableSocketAPI = False
quitFlag = False
batchIsOpen = False
readyToStart = False
finishedDisc = False
processingDisc = False
finishedBatch = False
