#! /usr/bin/env python3
"""Shared configuration constants"""

version = ""
inDevice = ""
aaruBin = ""
ddrescueBin = ""
imagingApplication = ""
blockSize = ""
retries = ""
rootDir = ""
batchFolder = ""
batchManifest = ""
secondsToTimeout = ""
prefixBatch = ""
socketHost = "127.0.0.1"
socketPort = "65432"
enablePPNLookup = True
enableSocketAPI = False
quitFlag = False
batchIsOpen = False
readyToStart = False
finishedMedium = False
processingMedium = False
finishedBatch = False
